clear
clc

cd 'C:\Users\dmsmi\Documents\textbook\html'
files = { ...
    'Preface.htm' ...
    '01_Introduction.htm' ...
    '02_Basics.htm' ...
    '03_Functions.htm' ...
    '04_Vectors.htm' ...
    '05_Execution.htm' ...
    '06_Strings.htm' ...
    '07_Structures.htm' ...
    '08_File_I_O.htm' ...
    '09_Recursion.htm' ...
    '10_Problem_Solving.htm' ...
    '11_Plotting.htm' ...
    '12_Matrices.htm' ...
    '13_Images.htm' ...
    '14_Sounds.htm' ...
    '15_Numerical_Methods.htm' ...
    '16_Sorting.htm' ...
    '17_Graphs.htm'};

ndx = 0;
in = fopen('dms_index.txt','r');
line = fgetl(in);
while ischar(line)
    ndx = ndx + 1;
    fprintf('%s\n', line)
    if ndx < 10
        double(line)
    end
    line = fgetl(in);
end
